# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 809be6f9b1a7e1204f39b5d297e7978d45556a0cfe8bcfad71474925b1cef9c9c554d42340aa6d387aa3325b6eeb6fe6d70220d3ce91cac0260e8e3350b8d44d

test:
  secret_key_base: bedfedeb7a7f2ecd09072558baade64518848c5ce2178914c6c411dc292c438287bb665fcd82553622372f18eda5d9bf2c948b31b23b29afcd31eb92676e4f39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
